### ISSUE TITLE
Not working at all in 1.13 or 18w30b

### ISSUE THREAD

**Issue by EarlyReflex** [Cubitect/ASMTick#13]
I wish this would actually work in 18w30b. That snapshot fixed a nasty village detection bug that killed pretty much every big iron farm in existence. 

This is the Python console after trying to install in 18w30b, every options checked:

```
Searching for mappings for ASMTick...
MinecraftServer -> net/minecraft/server/MinecraftServer
MinecraftServer.commandManager -> b
ServerCommandManager -> xr
MinecraftServer.updateTimeLightAndEntities -> b
WorldServer -> tc
PlayerList -> vo
CommandTime -> ()Ljava/util/ArrayList;
Disassembling ()Ljava/util/ArrayList;...
Traceback (most recent call last):
  File "C:\ASMModSuite\Krakatau-master\disassemble.py", line 63, in <module>
    disassembleClass(readTarget, targets, args.out, args.roundtrip)
  File "C:\ASMModSuite\Krakatau-master\disassemble.py", line 23, in disassembleClass
    data = readTarget(target)
  File "C:\ASMModSuite\Krakatau-master\disassemble.py", line 13, in readFile
    with open(filename, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'C:\\ASMModSuite\\cache\\18w30b\\classes\\()Ljava/util/ArrayList;.class'
```

This mod would be incredibly useful to help me debug my "Iron Towers" that still don't work in 18w30b. Any help will be greatly appreciated!

Python 2.7.12, Windows 10_64

**Comment by CJStanleyWinter** [comment]
Would also love to see this working in the 1.13.1 snapshots.
Upon attempting install it just says Mod could not be created.

Eternal gratefulness for you if you could make it work.

**Comment by ghost** [comment]
I contacted Cubitect a week ago, and he said that he probably won't have an opportunity to work on the ASM Mod Suit for at least a few weeks. His main focus right now is on his other mod, cubiomes.

**Comment by Sharkykzn** [comment]
Also get the following error:
`Mod 'ASMVillageMarker' could not be created.
View stdout for more information.

unsupported operand type(s) for +: 'NoneType' and 'int'`
Would be awesome to get the Village marker working in 1.13

**Comment by u1f98e** [comment]
I get the same error message in 1.13.1 for all the mods except ASM Tick, which instead gives:
`Mod 'ASMTick' could not be created. View stdout for more information

list indices must be integers, not NoneType`

**Comment by wdmartin** [comment]
Getting the same "unsupported operand type(s)" error with 1.13.1 and Python 2.7.8.  There was no especially useful info in stdout; it said this:

```
Searching for mappings for ASMVillageMarker...
404: ASMRender
Setting up ASMRender...
Main -> net/minecraft/client/main/Main
MinecraftServer -> net/minecraft/server/MinecraftServer
Minecraft -> k
```

**Comment by VoiceLessQ** [comment]
Any1 have 1.13.1 working jar i can have ?
